= Oixum

_Nota:_ ver PMBOK 4.1 (seria el primer proceso de la gestion de proyectos). Necesitamos un documento similar para empezar a planificar. Dejo subtitulos con las cosas que deberia contener el documento.

== Justificacion

Ver caso de negocio.

== Objetivos

-Participar de la feria de ciencias 2019 en sus intancias regional,juridiccional y regional.
-Desarrollar una aplicacion web de E-learning para uso interno de la escuela.
-Fomentar la aplicacion de tecnologias web para asistir el dictado de clases en la escuela.
-Fomentar el intercambio entre los alumnos que ejecuten el proyecto y los docentes de la escuela.

== Requisitos

Elaborar y analizar con un poco mas de detalle los objetivos. Que necesitamos hacer para cumplir los objetivos.

== Supuestos y restricciones

== Descripcion del alcance (preliminar)

Breve descripcion de lo que hay que hacer y los entregables.

== Cronograma de hitos (preliminar)

Al menos aca ya sabemos las fechas para la feria.

- (Viernes 28) ,hay que imprimir la grafica para el stand y cerrar el informe tecnico
- (5 de julio) (feria regional)
- Antes de la feria INNOVA (23 a 27 de septiembre), hay que imprimir la grafica para el stand y cerrar el informe tecnico
- Ultima semana de septiembre (feria INNOVA)
- Antes de la feria nacional (18 a 22 de noviembre) , hay que imprimir la grafica para el stand y cerrar el informe tecnico
- Ultima semana de noviembre probablemente (feria nacional)
- (Del 2 al 7 de Diciembre) , socializacion del proyecto a toda la escuela y expectativas para el proximo año y grupo.

Planificamos como que llegamos a la ultima instancia, total el proyecto sigue hasta diciembre independientemente de la feria

== Presupuesto (preliminar)

Autoexplicativo.

== Interesados o beneficiarios

Autoexplicativo.

== Equipo del proyecto( 4to 1era , 4to 2da y 4to 3ra)

- Abella Juan.
- Amigo Martin.
- Caputo Mateo.
- Delfino Tomas.
- Espindola Marcos.
- Rodriguez Facundo.
- Magre Leonel.
- Perree Matias.
- Sanchez Agustin.
- Abadi  Facundo.
- Alarcon Gonzalo.
- Benitez Matias. 
- Camisiro Jorge.
- Cingolani Nicolas. 
- Costenla Nicolas.
- D"Angelo Ariel.
- De La Fuente Matias.
- Diaz Agustin.
- Espinoza Emiliano.
- Estrada Erick.
- Garcia Lucas.
- Gerula Jonathan. 
- Humano Matias. 
- Iglesias Facundo.
- Jimenez Carolina.
- Kilberg Demian.
- Lesta Facundo.
- Licciardi Facundo.
- Marconi Miguel.
- Mendoza Franco.
- Panzitta Gustavo.
- Petean Marina.
- Quisbert Varinia.
- Romero Ignacio.
- Sosa Rodrigo.
- Spano Ramiro.
- Staltari Lucio. 
- Toscano Dylan.
- Valle Facundo.
- Vazquez Patricio.
- Velasco Cristian.
- Williams Alan.

La lista de todos nosotros y el nivel jerarquico de cada uno si aplicara.

No tiene que estar todo necesariamente. Vean el PMBOK para sacar ideas de que pueden escribir ahi, vean tambien lo que escribi para el rector para justificar los gastos en ploteos.
