= Oixum

_Nota:_ ver PMBOK 4.1 (seria el primer proceso de la gestion de proyectos). Necesitamos un documento similar para empezar a planificar. Dejo subtitulos con las cosas que deberia contener el documento.

== Justificacion

Ver caso de negocio.

== Objetivos

Que sean medibles y que se asocie el exito del proyecto a los mismos.

== Requisitos

Elaborar y analizar con un poco mas de detalle los objetivos. Que necesitamos hacer para cumplir los objetivos.

== Supuestos y restricciones

== Descripcion del alcance (preliminar)

Breve descripcion de lo que hay que hacer y los entregables.

== Cronograma de hitos (preliminar)

Al menos aca ya sabemos las fechas para la feria.

- 1 semana antes de la feria regional hay que imprimir la grafica para el stand y cerrar el informe tecnico
- 5 de julio (feria regional)
- 1 semana antes de la feria INNOVA hay que imprimir la grafica para el stand y cerrar el informe tecnico
- Ultima semana de septiembre (feria INNOVA)
- 1 semana antes de la feria nacional hay que imprimir la grafica para el stand y cerrar el informe tecnico
- Ultima semana de noviembre probablemente (feria nacional)
- Primera semana de diciembre, socializacion del proyecto a toda la escuela y expectativas para el proximo año y grupo.

Planificamos como que llegamos a la ultima instancia, total el proyecto sigue hasta diciembre independientemente de la feria

== Presupuesto (preliminar)

Autoexplicativo.

== Interesados o beneficiarios

Autoexplicativo.

== Equipo del proyecto

La lista de todos nosotros y el nivel jerarquico de cada uno si aplicara.

No tiene que estar todo necesariamente. Vean el PMBOK para sacar ideas de que pueden escribir ahi, vean tambien lo que escribi para el rector para justificar los gastos en ploteos.
